### ISSUE TITLE
[bug]Game Crash

### ISSUE THREAD

**Issue by Rad586** [KxmischesDomi/MoreAxolotls#12]
I tried to translate this mod to my language, nothing's wrong when initalizing the game, but it crashes when I open the "Axolotl Catalog"(I tried unicode but it still doesn't work). I would appreciate it if you coud fix that problem!Below is the log file.
[crash-2022-04-16_23.51.40-client.txt](https://github.com/KxmischesDomi/MoreAxolotls/files/8541651/crash-2022-04-16_23.51.40-client.txt)

It's mainly about...

Description: Rendering screen
java.lang.StackOverflowError: Rendering screen
	at net.minecraft.class_327.method_1727(class_327.java:362)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:235)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)
	at de.kxmischesdomi.more_axolotls.client.screen.AxolotlCatalogScreen.renderAxolotlInfoText(AxolotlCatalogScreen.java:263)

**Comment by DomiIRL** [comment]
Yea theres's a bug in the axolotl catalog text rendering code when a line is empty or in some other cases. I haven't discovered all yet. I'm currently not working on my mods, so I won't fix it any time very soon.

**Comment by DomiIRL** [comment]
Will be fixed with the next update.
We decided to remove the line break algorithm. So you will have to do that yourself in the future.
